trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t mylabacr2589.azurecr.io/web-game:tag 2048-game
      az acr login -n mylabacr2589
      docker push mylabacr2589.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Visual Studio Enterprise Subscription'
    azureResourceGroup: 'rg_prod'
    kubernetesCluster: 'mylab-aks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Visual Studio Enterprise Subscription'
    azureContainerRegistry: 'mylabacr2589.azurecr.io'
    forceUpdate: false
